input_channel: 3

depth_multiple: 1.0
width_multiple: 1.0

backbone:
    # [repeat, module, args]
    [
        [1, Conv, [32, 3, 2]],
        [1, MBConv, [1, 16, 1, 3]],
        [1, MBConv, [6, 24, 2, 3]],
        [1, MBConv, [6, 40, 2, 3]],
        [1, MBConv, [6, 80, 2, 3]],
        [1, MBConv, [6, 112, 1, 3]],
        [1, MBConv, [6, 192, 2, 3]],
        [1, MBConv, [6, 320, 1, 3]],
        [1, Conv, [128, 1, 1]],
        [1, GlobalAvgPool, []],
        [1, Conv, [9, 1, 1, null, 1, null]]
    ]

# delete one of MBConv from effientb0
