input_channel: 3

depth_multiple: 1.0
width_multiple: 1.0

backbone:
    # Example model in PyTorch Tutorial (https://pytorch.org/tutorials/beginner/blitz/cifar10_tutorial.html)
    # [repeat, module, args]
    [
        [1, Conv, [16,3,2]],
        [1, Fire, [8,12,12]],
        [1, Fire, [16,32,32]],
        [1, GlobalAvgPool, []],
        [1, Flatten, []],
        [1, Linear, [9]]
    ]
